name: Asset Sizes
"on":
  - pull_request
jobs:
  build:
    name: Calculate asset sizes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the entire repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
