name: Continuous Integration
'on':
  - push
jobs:
  test:
    name: Run tests
    runs-on: '${{ matrix.os }}'
    strategy:
      max-parallel: 4
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: 'Setup Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install volta
        uses: volta-cli/action@v1
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv
      - name: Cache .venv
        uses: actions/cache@v1
        id: cache-venv
        with:
          path: .venv
          key: ${{ runner.os }}-${{ hashFiles('Pipfile') }}-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('Pipfile') }}-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev --skip-lock
      - name: Update template variables
        run: |
          yarn demo:update
      - name: Run tests
        run: |
          yarn test